name: CI (default)

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test

      - name: Build without tests
        run: ./gradlew build -x test

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # See: https://github.com/marketplace/actions/build-with-gradle#the-dependency-submission-action
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
