name: CI (staging)

on:
  push:
    branches:
      - 'hotfix/**'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test

      - name: Build without tests
        run: ./gradlew build -x test

      - name: Upload JAR for promotion
        uses: actions/upload-artifact@v4
        with:
          name: staging-artifact
          path: build/libs/*.jar

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: staging-artifact

      - name: Deploy to STAGING (placeholder)
        run: echo "Deploying $(ls *.jar) to STAGING environment..."
        # TODO
