name: Release (production)

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  fetch-artifact:
    runs-on: ubuntu-latest

    steps:
      # See: https://github.com/marketplace/actions/download-workflow-artifact
      - name: Download artifact from staging build
        uses: dawidd6/action-download-artifact@v11
        with:
          name: staging-artifact
          workflow: build-staging.yml
          commit: ${{ github.sha }}
          path: ./artifact

      - name: Show content
        run: ls -R artifact

      - name: Upload to current run (for following jobs)
        uses: actions/upload-artifact@v4
        with:
          name: prod-artifact
          path: artifact/*.jar

  create-release:
    needs: fetch-artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: prod-artifact

      # See: https://github.com/marketplace/actions/gh-release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: "*.jar"

  deploy-production:
    needs: create-release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: prod-artifact
      - name: Deploy to PRODUCTION (placeholder)
        run: echo "Deploying $(ls *.jar) to PRODUCTION environment..."
        # TODO
